port: 7890
socks-port: 7891
allow-lan: false
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
unified-delay: true
hosts:
  time.facebook.com: 17.253.84.125
  time.android.com: 17.253.84.125
dns:
  enable: true
  use-hosts: true
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 223.6.6.6
    - tcp://223.5.5.5
    - tcp://223.6.6.6
    - tls://dns.google:853
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - tls://dns.alidns.com
    - tls://223.5.5.5
    - tls://223.6.6.6
    - tls://dot.pub
    - tls://1.12.12.12
    - tls://120.53.53.53
    - https://dns.google/dns-query
    - https://8.8.8.8/dns-query
    - https://8.8.4.4/dns-query
    - https://dns.alidns.com/dns-query
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query
    - https://doh.pub/dns-query
    - https://1.12.12.12/dns-query
    - https://120.53.53.53/dns-query
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 223.6.6.6
    - tcp://119.29.29.29
    - tcp://223.5.5.5
    - tcp://223.6.6.6
proxies:
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯Z01, server: qtx14-g04.hk01-ae5.entry.v50307shvkaa.art, port: 19274, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬Z01 | x0.8, server: v81ye-g04.jp01-ae5.entry.v50307shvkaa.art, port: 475, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯Z02 | IEPL, server: goov5-g04.hk02-ae5.entry.v50307shvkaa.art, port: 14562, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬Z02 | x0.8, server: vfiot-g04.jp02-ae5.entry.v50307shvkaa.art, port: 485, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯Z03 | IEPL, server: zag5c-g04.hk03-ae5.entry.v50307shvkaa.art, port: 762, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬Z03 | x0.8, server: pobm0-g04.jp03-ae5.entry.v50307shvkaa.art, port: 490, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯Z04 | IEPL, server: qoatl-g04.hk04-ae5.entry.v50307shvkaa.art, port: 806, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬Z04 | x0.8, server: 65xlh-g04.jp04-ae5.entry.v50307shvkaa.art, port: 495, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯Z05 | IEPL, server: vrjkb-g04.hk05-ae5.entry.v50307shvkaa.art, port: 1814, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬Z05 | ä¸‹è½½ä¸“ç”¨ | x0.01, server: w9geu-g04.jp05-vm5.entry.rtysjur.quest, port: 64657, type: vmess, uuid: 1111013a-6eb8-318f-bc76-a2f6d46b8896, alterId: 1, cipher: auto, tls: false, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯Z06 | x0.8, server: kuv17-g04.hk06-ae5.entry.v50307shvkaa.art, port: 1415, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬Z06 | ä¸‹è½½ä¸“ç”¨ | x0.01, server: 2sby4-g04.jp06-vm5.entry.rtysjur.quest, port: 665, type: vmess, uuid: 1111013a-6eb8-318f-bc76-a2f6d46b8896, alterId: 1, cipher: auto, tls: false, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯Z07 | x0.8, server: 6420f-g04.hk07-ae5.entry.v50307shvkaa.art, port: 1422, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬Z07 | x0.8, server: i8ddn-g04.jp07-ae5.entry.v50307shvkaa.art, port: 14007, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯Z08 | x0.8, server: 5zcab-g04.hk08-ae5.entry.v50307shvkaa.art, port: 18645, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬Z08 | x0.8, server: 8ue0a-g04.jp08-ae5.entry.v50307shvkaa.art, port: 12545, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯Z09 | IEPL, server: 0tvq6-g04.hk09-vm5.entry.v50307shvkaa.art, port: 15267, type: vmess, uuid: 1111013a-6eb8-318f-bc76-a2f6d46b8896, alterId: 1, cipher: auto, tls: false, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬Z09 | x0.8, server: zvwxq-g04.jp09-ae5.entry.v50307shvkaa.art, port: 11160, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯Z10 | IEPL, server: sd8lg-g04.hk10-vm5.entry.v50307shvkaa.art, port: 13485, type: vmess, uuid: 1111013a-6eb8-318f-bc76-a2f6d46b8896, alterId: 1, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-opts: {path: /, headers: {Host: bgp-01-10.entry-0.chinasnow.net}}, udp: true}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬Z10 | x0.8, server: f828k-g04.jp10-ae5.entry.v50307shvkaa.art, port: 16526, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯Z11 | IEPL, server: qjcng-g04.hk11-vm5.entry.v50307shvkaa.art, port: 577, type: vmess, uuid: 1111013a-6eb8-318f-bc76-a2f6d46b8896, alterId: 1, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-opts: {path: /tutorial/iphone13.m3u8, headers: {Host: bgp-01-11.entry-0.chinasnow.net}}, udp: true}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬Z11 | x0.8, server: 712kh-g04.jp11-ae5.entry.v50307shvkaa.art, port: 17743, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬Z12 | IEPL | æµ‹è¯•, server: ffcsm-g04.jp12-ae5.entry.v50307shvkaa.art, port: 500, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡Z01, server: gusip-g04.sg01-ae5.entry.v50307shvkaa.art, port: 20002, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡Z02, server: 8f723-g04.sg02-ae5.entry.v50307shvkaa.art, port: 20077, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡Z03 | IEPL | x2, server: 75kpd-g04.sg03-ae5.entry.v50307shvkaa.art, port: 20082, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡¨ğŸ‡³ å°æ¹¾Z01 | IEPL | x2, server: k5mq8-g04.tw01-ae5.entry.v50307shvkaa.art, port: 20007, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡ºğŸ‡² ç¾å›½Z01, server: z9utx-g04.us01-ae5.entry.v50307shvkaa.art, port: 20012, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡ºğŸ‡² ç¾å›½Z02, server: tspq5-g04.us02-ae5.entry.v50307shvkaa.art, port: 20017, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡¬ğŸ‡§ è‹±å›½Z01, server: 3jpby-g04.gb01-ae5.entry.v50307shvkaa.art, port: 20022, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡¦ğŸ‡· é˜¿æ ¹å»·Z01, server: gpsie-g04.ar01-ae5.entry.v50307shvkaa.art, port: 20027, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡·ğŸ‡º ä¿„ç½—æ–¯Z01, server: kji1h-g04.ru01-ae5.entry.v50307shvkaa.art, port: 20032, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡¹ğŸ‡· åœŸè€³å…¶Z01, server: 8b1y0-g04.tr01-ae5.entry.v50307shvkaa.art, port: 20037, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡°ğŸ‡· éŸ©å›½Z01, server: swmn1-g04.kr01-ae5.entry.v50307shvkaa.art, port: 20042, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡®ğŸ‡³ å°åº¦Z01, server: 2as1n-g04.in01-ae5.entry.v50307shvkaa.art, port: 20047, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡©ğŸ‡ª å¾·å›½Z01, server: 2mhs5-g04.de01-ae5.entry.v50307shvkaa.art, port: 20052, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡¨ğŸ‡¦ åŠ æ‹¿å¤§Z01, server: n3rc8-g04.ca01-ae5.entry.v50307shvkaa.art, port: 20057, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡¦ğŸ‡º æ¾³å¤§åˆ©äºšZ01, server: pjum5-g04.au01-ae5.entry.v50307shvkaa.art, port: 20062, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡«ğŸ‡· æ³•å›½Z01, server: 7dvic-g04.fr01-ae5.entry.v50307shvkaa.art, port: 20067, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡ºğŸ‡¦ ä¹Œå…‹å…°Z01, server: 4oumh-g04.ua01-ae5.entry.v50307shvkaa.art, port: 20072, type: ss, cipher: aes-256-gcm, password: 1111013a-6eb8-318f-bc76-a2f6d46b8896, udp: true}
  - {name: ğŸ‡¯ğŸ‡µ å…è´¹-æ—¥æœ¬1-Ver.6, server: cer8h-g04.jp01-0986-vm0.entry.fr0307a.art, port: 21584, type: vmess, uuid: 1111013a-6eb8-318f-bc76-a2f6d46b8896, alterId: 1, cipher: auto, tls: true, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡¯ğŸ‡µ å…è´¹-æ—¥æœ¬2-Ver.7, server: r0ghk-g04.jp02-9a99-vm0.entry.fr0307a.art, port: 11776, type: vmess, uuid: 1111013a-6eb8-318f-bc76-a2f6d46b8896, alterId: 1, cipher: auto, tls: false, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡¯ğŸ‡µ å…è´¹-æ—¥æœ¬3-Ver.6, server: xagd0-g04.jp03-7d22-vm0.entry.fr0307a.art, port: 21584, type: vmess, uuid: 1111013a-6eb8-318f-bc76-a2f6d46b8896, alterId: 1, cipher: auto, tls: true, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡¯ğŸ‡µ å…è´¹-æ—¥æœ¬4-Ver.7, server: 2x5vl-g04.jp04-3771-vm0.entry.fr0307a.art, port: 447, type: vmess, uuid: 1111013a-6eb8-318f-bc76-a2f6d46b8896, alterId: 1, cipher: auto, tls: false, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡¯ğŸ‡µ å…è´¹-æ—¥æœ¬5-Ver.8, server: agkip-g04.jp05-6786-vm0.entry.fr0307a.art, port: 46485, type: vmess, uuid: 1111013a-6eb8-318f-bc76-a2f6d46b8896, alterId: 1, cipher: auto, tls: false, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡¯ğŸ‡µ å…è´¹-æ—¥æœ¬6-Ver.7, server: fd8e8-g04.jp06-7c5a-vm0.entry.fr0307a.art, port: 28786, type: vmess, uuid: 1111013a-6eb8-318f-bc76-a2f6d46b8896, alterId: 1, cipher: auto, tls: true, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡¯ğŸ‡µ å…è´¹-æ—¥æœ¬7-Ver.1, server: wj94f-g04.jp07-1f28-vm0.entry.fr0307a.art, port: 28786, type: vmess, uuid: 1111013a-6eb8-318f-bc76-a2f6d46b8896, alterId: 1, cipher: auto, tls: false, skip-cert-verify: false, udp: true}
proxy-groups:
  - name: é€‰æ‹©èŠ‚ç‚¹
    type: select
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯Z01
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬Z01 | x0.8
      - ğŸ‡­ğŸ‡° é¦™æ¸¯Z02 | IEPL
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬Z02 | x0.8
      - ğŸ‡­ğŸ‡° é¦™æ¸¯Z03 | IEPL
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬Z03 | x0.8
      - ğŸ‡­ğŸ‡° é¦™æ¸¯Z04 | IEPL
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬Z04 | x0.8
      - ğŸ‡­ğŸ‡° é¦™æ¸¯Z05 | IEPL
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬Z05 | ä¸‹è½½ä¸“ç”¨ | x0.01
      - ğŸ‡­ğŸ‡° é¦™æ¸¯Z06 | x0.8
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬Z06 | ä¸‹è½½ä¸“ç”¨ | x0.01
      - ğŸ‡­ğŸ‡° é¦™æ¸¯Z07 | x0.8
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬Z07 | x0.8
      - ğŸ‡­ğŸ‡° é¦™æ¸¯Z08 | x0.8
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬Z08 | x0.8
      - ğŸ‡­ğŸ‡° é¦™æ¸¯Z09 | IEPL
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬Z09 | x0.8
      - ğŸ‡­ğŸ‡° é¦™æ¸¯Z10 | IEPL
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬Z10 | x0.8
      - ğŸ‡­ğŸ‡° é¦™æ¸¯Z11 | IEPL
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬Z11 | x0.8
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬Z12 | IEPL | æµ‹è¯•
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡Z01
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡Z02
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡Z03 | IEPL | x2
      - ğŸ‡¨ğŸ‡³ å°æ¹¾Z01 | IEPL | x2
      - ğŸ‡ºğŸ‡² ç¾å›½Z01
      - ğŸ‡ºğŸ‡² ç¾å›½Z02
  - name: æœªåŒ¹é…
    type: select
    proxies:
      - DIRECT
      - é€‰æ‹©èŠ‚ç‚¹



rule-providers:
  æˆ‘çš„ä»£ç†:
    behavior: classical
    type: http
    url: "https://raw.gitmirror.com/cz-97/proxy/main/proxy.txt"
    format: "text"
    interval: 86400
    path: ./æˆ‘çš„ä»£ç†.txt

  æˆ‘çš„ç›´è¿:
    behavior: classical
    type: http
    url: "https://raw.gitmirror.com/cz-97/proxy/main/direct.txt"
    format: "text"
    interval: 86400
    path: ./æˆ‘çš„ç›´è¿.txt

  å¹¿å‘Š:
    type: http
    behavior: domain
    url: "https://raw.gitmirror.com/Loyalsoldier/clash-rules/release/reject.txt"
    path: ./ruleset/å¹¿å‘Š.yaml
    interval: 86400

  éä¸­å›½é¡¶åŸŸ:
    type: http
    behavior: domain
    url: "https://raw.gitmirror.com/Loyalsoldier/clash-rules/release/tld-not-cn.txt"
    path: ./ruleset/éä¸­å›½é¡¶åŸŸ.yaml
    interval: 86400

  çº¸é£æœºIP:
    type: http
    behavior: ipcidr
    url: "https://raw.gitmirror.com/Loyalsoldier/clash-rules/release/telegramcidr.txt"
    path: ./ruleset/çº¸é£æœºIP.yaml
    interval: 86400

  è¿œç¨‹ç›´è¿:
    type: http
    behavior: domain
    url: "https://raw.gitmirror.com/Loyalsoldier/clash-rules/release/direct.txt"
    path: ./ruleset/è¿œç¨‹ç›´è¿.yaml
    interval: 86400

  å¤§é™†IP:
    type: http
    behavior: ipcidr
    url: "https://raw.gitmirror.com/Loyalsoldier/clash-rules/release/cncidr.txt"
    path: ./ruleset/å¤§é™†IP.yaml
    interval: 86400

  ç§æœ‰åŸŸ:
    type: http
    behavior: domain
    url: "https://raw.gitmirror.com/Loyalsoldier/clash-rules/release/private.txt"
    path: ./ruleset/ç§æœ‰åŸŸ.yaml
    interval: 86400

  å±€åŸŸç½‘IPåŠä¿ç•™IP:
    type: http
    behavior: ipcidr
    url: "https://raw.gitmirror.com/Loyalsoldier/clash-rules/release/lancidr.txt"
    path: ./ruleset/å±€åŸŸç½‘IPåŠä¿ç•™IP.yaml
    interval: 86400

  è¿œç¨‹ä»£ç†:
    type: http
    behavior: domain
    url: "https://raw.gitmirror.com/Loyalsoldier/clash-rules/release/proxy.txt"
    path: ./ruleset/è¿œç¨‹ä»£ç†.yaml
    interval: 86400

rules:
  - RULE-SET,å¹¿å‘Š,REJECT
  - RULE-SET,è¿œç¨‹ç›´è¿,DIRECT
  - RULE-SET,ç§æœ‰åŸŸ,DIRECT
  - RULE-SET,å¤§é™†IP,DIRECT
  - RULE-SET,å±€åŸŸç½‘IPåŠä¿ç•™IP,DIRECT
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - RULE-SET,æˆ‘çš„ä»£ç†,é€‰æ‹©èŠ‚ç‚¹
  - RULE-SET,æˆ‘çš„ç›´è¿,DIRECT
  - RULE-SET,è¿œç¨‹ä»£ç†,é€‰æ‹©èŠ‚ç‚¹
  - RULE-SET,éä¸­å›½é¡¶åŸŸ,é€‰æ‹©èŠ‚ç‚¹
  - RULE-SET,çº¸é£æœºIP,é€‰æ‹©èŠ‚ç‚¹
  - MATCH,æœªåŒ¹é…

